// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPjS5BWF9v3hVDPNIhY8O7IdB4Sry-RSI',
    appId: '1:562337692200:web:c881f977d3a296c9c9931d',
    messagingSenderId: '562337692200',
    projectId: 'social-app-834ec',
    authDomain: 'social-app-834ec.firebaseapp.com',
    storageBucket: 'social-app-834ec.appspot.com',
    measurementId: 'G-VXPVWKCG05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZmaVTgjHLSNRsOZJxd0u-L51DYuya8g8',
    appId: '1:562337692200:android:7324a90007453a91c9931d',
    messagingSenderId: '562337692200',
    projectId: 'social-app-834ec',
    storageBucket: 'social-app-834ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0tDMBBoU0T5A3PtVyJri6VsV8OeVbOXM',
    appId: '1:562337692200:ios:10d556c21fed83c6c9931d',
    messagingSenderId: '562337692200',
    projectId: 'social-app-834ec',
    storageBucket: 'social-app-834ec.appspot.com',
    iosBundleId: 'com.example.socialTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0tDMBBoU0T5A3PtVyJri6VsV8OeVbOXM',
    appId: '1:562337692200:ios:10d556c21fed83c6c9931d',
    messagingSenderId: '562337692200',
    projectId: 'social-app-834ec',
    storageBucket: 'social-app-834ec.appspot.com',
    iosBundleId: 'com.example.socialTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPjS5BWF9v3hVDPNIhY8O7IdB4Sry-RSI',
    appId: '1:562337692200:web:8583d2333c8b580dc9931d',
    messagingSenderId: '562337692200',
    projectId: 'social-app-834ec',
    authDomain: 'social-app-834ec.firebaseapp.com',
    storageBucket: 'social-app-834ec.appspot.com',
    measurementId: 'G-K9HZ6F97VK',
  );
}
